# Generated by Django 5.1.7 on 2025-04-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_city_remove_user_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='AC',
        ),
        migrations.RemoveField(
            model_name='house',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='house',
            name='state',
        ),
    ]
