# Generated by Django 5.1.7 on 2025-06-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_house_ac_remove_house_hall_remove_house_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='balcany',
            new_name='balcony',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='balcany',
            new_name='balcony',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='dimention',
            new_name='dimension',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
